/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'
import { Route as AuthenticatedColeccionRouteImport } from './routes/_authenticated/coleccion'
import { Route as AuthenticatedEscanerRouteImport } from './routes/_authenticated/escaner'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedProxiesRouteImport } from './routes/_authenticated/proxies'
import { Route as AuthenticatedRegistroRouteImport } from './routes/_authenticated/registro'
import { Route as AuthenticatedResumenRouteImport } from './routes/_authenticated/resumen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedColeccionRoute = AuthenticatedColeccionRouteImport.update({
  id: '/coleccion',
  path: '/coleccion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscanerRoute = AuthenticatedEscanerRouteImport.update({
  id: '/escaner',
  path: '/escaner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProxiesRoute = AuthenticatedProxiesRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegistroRoute = AuthenticatedRegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumenRoute = AuthenticatedResumenRouteImport.update({
  id: '/resumen',
  path: '/resumen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/coleccion': typeof AuthenticatedColeccionRoute
  '/escaner': typeof AuthenticatedEscanerRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/proxies': typeof AuthenticatedProxiesRoute
  '/registro': typeof AuthenticatedRegistroRoute
  '/resumen': typeof AuthenticatedResumenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/coleccion': typeof AuthenticatedColeccionRoute
  '/escaner': typeof AuthenticatedEscanerRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/proxies': typeof AuthenticatedProxiesRoute
  '/registro': typeof AuthenticatedRegistroRoute
  '/resumen': typeof AuthenticatedResumenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/coleccion': typeof AuthenticatedColeccionRoute
  '/_authenticated/escaner': typeof AuthenticatedEscanerRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/proxies': typeof AuthenticatedProxiesRoute
  '/_authenticated/registro': typeof AuthenticatedRegistroRoute
  '/_authenticated/resumen': typeof AuthenticatedResumenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/ajustes'
    | '/coleccion'
    | '/escaner'
    | '/panel'
    | '/proxies'
    | '/registro'
    | '/resumen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/ajustes'
    | '/coleccion'
    | '/escaner'
    | '/panel'
    | '/proxies'
    | '/registro'
    | '/resumen'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/ajustes'
    | '/_authenticated/coleccion'
    | '/_authenticated/escaner'
    | '/_authenticated/panel'
    | '/_authenticated/proxies'
    | '/_authenticated/registro'
    | '/_authenticated/resumen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coleccion': {
      id: '/_authenticated/coleccion'
      path: '/coleccion'
      fullPath: '/coleccion'
      preLoaderRoute: typeof AuthenticatedColeccionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escaner': {
      id: '/_authenticated/escaner'
      path: '/escaner'
      fullPath: '/escaner'
      preLoaderRoute: typeof AuthenticatedEscanerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proxies': {
      id: '/_authenticated/proxies'
      path: '/proxies'
      fullPath: '/proxies'
      preLoaderRoute: typeof AuthenticatedProxiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registro': {
      id: '/_authenticated/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof AuthenticatedRegistroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumen': {
      id: '/_authenticated/resumen'
      path: '/resumen'
      fullPath: '/resumen'
      preLoaderRoute: typeof AuthenticatedResumenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedColeccionRoute: typeof AuthenticatedColeccionRoute
  AuthenticatedEscanerRoute: typeof AuthenticatedEscanerRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedProxiesRoute: typeof AuthenticatedProxiesRoute
  AuthenticatedRegistroRoute: typeof AuthenticatedRegistroRoute
  AuthenticatedResumenRoute: typeof AuthenticatedResumenRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedColeccionRoute: AuthenticatedColeccionRoute,
  AuthenticatedEscanerRoute: AuthenticatedEscanerRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedProxiesRoute: AuthenticatedProxiesRoute,
  AuthenticatedRegistroRoute: AuthenticatedRegistroRoute,
  AuthenticatedResumenRoute: AuthenticatedResumenRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
